### ISSUE TITLE
Evaluation and admissibility

### ISSUE THREAD

**Issue by g4v4g4i** [g4v4g4i/ArgABM#8]
Currently the evaluation rates theories as follows:
T1 > T2 iff T1 has more defended arguments than T2.

Alternatively we could think about calculating this relative to the size of the theory.

Option 1:
T1 > T2 iff |defended-args(T1)| / |discovered-args(T1)| > |defended-args(T2)| / |discovered-args(T2)|

Option 2:
T1 > T2 iff |non-defended-args(T1)| / |discovered-args(T1)| < |non-defended-args(T2)| / |discovered-args(T2)|

Option 3: hybrid between option 1 and option 2.

I would suggest to implement three procedures in behavior.nls and an option in the interface to choose.

**Comment by daimpi** [comment]
Is it the case that discovered-args = defended-args + non-defended-args ? B/c in this case Option 1 & 2 would be equivalent imho.

**Comment by g4v4g4i** [comment]
Good observation (and then option 3 is redundant as well). 

Maybe though, in future when we begin to model the explanatory power of arguments, these sums may get weighted (each arguments has a weight which mirrors its explanatory powre) and then the options may differ. So maybe it's worth keeping this in mind.

**Comment by daimpi** [comment]
I agree. Maybe we  (and in particular @dunjaseselja) can think even more general about how scientist in the real evaluate theories and from there get to ideas how this is best mimicked in our model. E.g. Maybe theories with lots of explored arguments get a decisive advantage in the real world which would be an argument against normalization ( dividing by "discovered-args"), but maybe not. What do you think? :)

**Comment by dunjaseselja** [comment]
I think that the more a theory is discovered/explored, the more scientists expect it to be supported by evidence (so,while young theories are forgiven for having anomalies, the older the theory gets, the less forgiving we are towards we anomalies we encounter). This would speak in favor of taking both the size of the theory and the level of its exploration (color of arguments) into account, but maybe that'd be an overkill. So we could go for taking into account just the size.
Once we introduce explanatory power into the theory, the defensibility will anyway be just one criterion, combined with others, so I wouldn't complicate it too much if possible.

**Comment by daimpi** [comment]
Just a short update on what we have been discussing recently regarding this topic:
Dunja's suggestion from above would actually speak for a metric which is the opposite of a normalization: rather than dividing by |discovered-args| it would mean multiplying by them:

- T1 > T2 iff |non-defended-args(T1)| * |discovered-args(T1)| < |non-defended-args(T2)| * |discovered-args(T2)|

or more generally:

- T1 > T2 iff |non-defended-args(T1)| * f(|discovered-args(T1)|) < |non-defended-args(T2)| * f(|discovered-args(T2)|)

where f(.) is a function which increases in |discovered-args|.

An obvious alternative would o/c be to go a middle way between normalization and multiplication:
- T1 > T2 iff |non-defended-args(T1)| < |non-defended-args(T2)| 

When discussing this Dunja thought that maybe trying out all of the alternatives (_normalization_, _multiplication_ and the _middle way_) for a specific parameter set (e.g. reliable agents,…).

This is something we can maybe discuss in more detail in Bamberg :).
